# Information Retrieval. Lab 1: Python fundementals + Indexing

## Introduction

The aim of **part 1** of this lab is for students to recap some **python fundementals**, and key packages such as *numpy* and *pandas* which we'll be using extensively throughout this module. We'll be executing code in a *notebook* environment, and it is suggested that you use *Google Colab* to do so. Not only is this easy to access, but it means that everyone is using the same python environment.

In **part 2** of this lab, we will familiarise ourselves with **indexing**, a concept learnt in Week 2. Specifically, we'll learn to build an index from natural text. we'll look at methods to calculate the **binary term-document matrix**, **document frequency**, and the **term-document count matrix**

# Part 1: Python Fundementals

## Introduction to Colab

Colab is a simple online Python notebook environment that comes with lots of packages preinstalled.

In [4]:
# Use the Play (▷) button next to each cell to run that cell,
# The (↑↓) buttons to change the order of cells

print('Welcome to Information Retrieval labs !')

Welcome to Information Retrieval labs !

In [ ]:
## To allow filesharing you can connect Colab with your Google Drive files by running the code below
# Follow the instructions in the pop up window to authorise access.
# You can now see your Drive folder and access files if you click on the filesharing tab on the left menu.

from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [5]:
## [CODING TIP] Colab Shortcuts

# Shift + Enter to run a cell
# B to add a new cell below
# A to add a new cell above

# You can discover more by going to Tools > Keyboard Shortcuts

## Python Recap

We'll be using several common Python packages and inbuilt functions in this module. Lets review them.

**If you are already very comfortable with python, feel free to skip and go straight to the tasks**

In [6]:
## For loops and If statements

for i in range(10):    # iterate over a range of 10.. i.e i=0,1,2,3,4,...,9
  if i % 2 == 0:       # if i is even, print i
    print(i)

0
2
4
6
8

In [7]:
## This can also be written more concisely using list comprehension
x = [print(i) for i in range(10) if i % 2 == 0]

0
2
4
6
8

In [8]:
## Functions: These are particularly useful if you want to repeat a process multiple times

def multiply (a, b): # this function takes two elements, and multiplies them.
  return a*b

for n in range(2,5):
  output = multiply(n, n+1)
  print(output)

6
12
20

In [9]:
## What is a set? A set is a unordered collection of unique items

# Note how the output set removes any duplicates
print(set([2,2,3,4]))

# The Intersection (&) of two sets is a set of items that are common to both sets
print(set([2,3,4]) & set([2]))

# The Union (|) of two sets is a set of all elements from both sets
print(set([2,3,4]) | set([2]))

# you can also use set.union() and set.intersection()

{2, 3, 4}
{2}
{2, 3, 4}

In [10]:
## Pandas is a package used to work with structural or tabular data.

import pandas as pd

# Lets start by reading a csv file containing information about california housing to a pandas' DataFrame.
df = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [11]:
# display dataframe
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [12]:
# Exploring some dataframe functions
print('Dimensions of dataframe:', df.shape)
print('\nDataframe attribute (column) names:\n', df.columns)
print('\nBasic statistics about dataframe:\n', df.describe())

Dimensions of dataframe: (17000, 9)

Dataframe attribute (column) names:
 Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

Basic statistics about dataframe:
           longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000
mean    -119.562108     35.625225           28.589353   2643.664412
std        2.005166      2.137340           12.586937   2179.947071
min     -124.350000     32.540000            1.000000      2.000000
25%     -121.790000     33.930000           18.000000   1462.000000
50%     -118.490000     34.250000           29.000000   2127.000000
75%     -118.000000     37.720000           37.000000   3151.250000
max     -114.310000     41.950000           52.000000  37937.000000

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000
mean       539.410824   1429.573941    501.221941       3.883578
std        421.499452   1147.852959    384.520841       1.908157
min          1.000000      3.000000      1.000000       0.499900
25%        297.000000    790.000000    282.000000       2.566375
50%        434.000000   1167.000000    409.000000       3.544600
75%        648.250000   1721.000000    605.250000       4.767000
max       6445.000000  35682.000000   6082.000000      15.000100

       median_house_value
count        17000.000000
mean        207300.912353
std         115983.764387
min          14999.000000
25%         119400.000000
50%         180400.000000
75%         265000.000000
max         500001.000000

In [13]:
# Column data can be selected using the following syntax: df[column name]
print('Values for the DataFrame attribute `total rooms`:\n', df['total_rooms'])

Values for the DataFrame attribute `total rooms`:
 0        5612.0
1        7650.0
2         720.0
3        1501.0
4        1454.0
          ...
16995    2217.0
16996    2349.0
16997    2677.0
16998    2672.0
16999    1820.0
Name: total_rooms, Length: 17000, dtype: float64

In [14]:
# However, this is more 'old school' python, and a more modern technique to select column and row data is to use the `iloc` and `loc` functions:
# The syntax for 'loc' is as follows: df.loc[row name,column name]
print(df.loc[1, 'longitude'])
print(df.loc[16999, 'population'])

-114.47
806.0

In [15]:
# ':' can be used to return all data for that row or column
print(df.loc[:, 'latitude'])

0        34.19
1        34.40
2        33.69
3        33.64
4        33.57
         ...
16995    40.58
16996    40.69
16997    41.84
16998    41.80
16999    40.54
Name: latitude, Length: 17000, dtype: float64

In [16]:
# 'iloc' works the same way but we use the index numbers for columns/rows rather than the names
# e.g df.iloc[row index, column index]
print(df.iloc[0,0])   # selecting data from the first column and first row
print(df.iloc[4,:])   # selecting all data from fifth row.

-114.31
longitude              -114.570
latitude                 33.570
housing_median_age       20.000
total_rooms            1454.000
total_bedrooms          326.000
population              624.000
households              262.000
median_income             1.925
median_house_value    65500.000
Name: 4, dtype: float64

In [17]:
## Official documentation is your friend.
# e.g Not sure how to use a pandas dataframe function?  Look up the documentation: https://pandas.pydata.org/docs/reference/frame.html

In [18]:
## For basic math functions and vector/matrix representation, numpy is an excellent package

import numpy as np

In [19]:
# An array is a python data structure, like a list, but with additional functionality
x = np.array([2,-10,2,-7,5])

print('Mean of array: ',np.mean(x))
print('Minimum value in array: ',np.min(x))
print('Absolute values of array: ',np.abs(x))
print('Dimensions of array: ',np.shape(x))

Mean of array:  -1.6
Minimum value in array:  -10
Absolute values of array:  [ 2 10  2  7  5]
Dimensions of array:  (5,)

In [20]:
# For example an array can represent data of multiple dimensions
df_np = np.array(df)
print(df_np)
print(df_np.shape)

[[-1.1431e+02  3.4190e+01  1.5000e+01 ...  4.7200e+02  1.4936e+00
   6.6900e+04]
 [-1.1447e+02  3.4400e+01  1.9000e+01 ...  4.6300e+02  1.8200e+00
   8.0100e+04]
 [-1.1456e+02  3.3690e+01  1.7000e+01 ...  1.1700e+02  1.6509e+00
   8.5700e+04]
 ...
 [-1.2430e+02  4.1840e+01  1.7000e+01 ...  4.5600e+02  3.0313e+00
   1.0360e+05]
 [-1.2430e+02  4.1800e+01  1.9000e+01 ...  4.7800e+02  1.9797e+00
   8.5800e+04]
 [-1.2435e+02  4.0540e+01  5.2000e+01 ...  2.7000e+02  3.0147e+00
   9.4600e+04]]
(17000, 9)

In [21]:
## To iterate through a numpy array or pandas dataframe, it is possible to use for loops.
# However, these can be inefficient especially with large datasets
# The preferred method is to use inbuilt numpy or pandas functions that support *vectorization*

import time

# random array of integers
x = np.random.randint(low=0, high=20, size=100, dtype=int)
y = np.random.randint(low=0, high=20, size=100, dtype=int)

# addition of x and y using for loops
start = time.time()
for i in range(100):
  output = [xi+yi for (xi, yi) in zip(x, y)]
end = time.time()
print('For loop addition. time taken {:.5f}s'.format(end-start))

# addition of x and y using numpy
start = time.time()
for i in range(100):
  output = x + y
end = time.time()
print('Numpy addition. time taken {:.5f}s'.format(end-start))

# Try changing the size of x and y. What do you observe in the time taken to execute the code?

For loop addition. time taken 0.00408s
Numpy addition. time taken 0.00032s

## Bash Commands

In [ ]:
# Bash commands are usually reserved for the terminal or command line, however you can use some simple ones in Colab

# e.g To install a new package that does not come preinstalled in Colab
!pip install nbconvert

Requirement already satisfied: nbconvert in /usr/local/lib/python3.10/dist-packages (6.5.4)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from nbconvert) (4.9.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from nbconvert) (4.11.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from nbconvert) (6.1.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.10/dist-packages (from nbconvert) (0.7.1)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.10/dist-packages (from nbconvert) (0.4)
Requirement already satisfied: jinja2>=3.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert) (3.1.3)
Requirement already satisfied: jupyter-core>=4.7 in /usr/local/lib/python3.10/dist-packages (from nbconvert) (5.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.10/dist-packages (from nbconvert) (0.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert) (2.1.4)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert) (0.8.4)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert) (0.9.0)
Requirement already satisfied: nbformat>=5.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert) (5.9.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from nbconvert) (23.2)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert) (1.5.1)
Requirement already satisfied: pygments>=2.4.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert) (2.16.1)
Requirement already satisfied: tinycss2 in /usr/local/lib/python3.10/dist-packages (from nbconvert) (1.2.1)
Requirement already satisfied: traitlets>=5.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert) (5.7.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/dist-packages (from jupyter-core>=4.7->nbconvert) (4.1.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.10/dist-packages (from nbclient>=0.5.0->nbconvert) (6.1.12)
Requirement already satisfied: fastjsonschema in /usr/local/lib/python3.10/dist-packages (from nbformat>=5.1->nbconvert) (2.19.1)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.10/dist-packages (from nbformat>=5.1->nbconvert) (4.19.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->nbconvert) (2.5)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from bleach->nbconvert) (1.16.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->nbconvert) (0.5.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert) (0.32.1)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert) (0.17.1)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.10/dist-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert) (23.2.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.10/dist-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert) (2.8.2)
Requirement already satisfied: tornado>=4.1 in /usr/local/lib/python3.10/dist-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert) (6.3.2)

In [ ]:
# Or to download an internet file into colab
!wget https://i.ytimg.com/vi/RJIABsgnTHk/maxresdefault.jpg
# once downloaded you can view this file on the files tab on the left menu (in the "content" folder).

--2024-01-26 11:14:09--  https://i.ytimg.com/vi/RJIABsgnTHk/maxresdefault.jpg
Resolving i.ytimg.com (i.ytimg.com)... 142.251.167.119, 142.251.16.119, 172.253.62.119, ...
Connecting to i.ytimg.com (i.ytimg.com)|142.251.167.119|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 32386 (32K) [image/jpeg]
Saving to: ‘maxresdefault.jpg’

maxresdefault.jpg   100%[===================>]  31.63K  --.-KB/s    in 0s

2024-01-26 11:14:09 (113 MB/s) - ‘maxresdefault.jpg’ saved [32386/32386]

## Tasks

### Question 1:
Write a function that takes a list of numbers and returns pairs of number from the list which add up to 10.

Test your function with **a few different dummy inputs**. Does your function cover all possible inputs?

In [22]:
def find_pairs(numbers):

  pairs = []
  seen_numbers = set()

  for num in numbers:
      complement = 10 - num

      if complement in seen_numbers:
          pairs.append((complement, num))

      seen_numbers.add(num)

  return pairs

x = [2, 3, 5, 4, 7, 6, 4, 8, 4]
find_pairs(x)

[(3, 7), (4, 6), (6, 4), (2, 8), (6, 4)]

### Question 2:
Write a function that takes our previous housing df as input, selects data entries with households greater than 450, and returns the mean population of that selection.

Test your function with some dummy inputs.

In [30]:
def find_population_mean_household_greater_than_450(input_df):
  # your code goes here

  filtered_df = input_df.loc[input_df['households'] > 450]['population'].mean()

  return filtered_df

# Test with the house dataframe
find_population_mean_household_greater_than_450(df)

2186.5214061003967

In [32]:
# Test with other inputs. Is the output the same as when you calculate this by hand?
dummy_df = pd.DataFrame(data={'households': [100, 500, 600], 'population': [400, 2000, 2400]})
find_population_mean_household_greater_than_450(dummy_df)

2200.0

Can you think of a single-line solution?

**[HINT]** Have a look at pandas.DataFrame.loc documentation.

### Question 3:
Create a function that takes a number N, squares every digit of that number and returns a concatenation of that number

e.g N = 75, returns 4925 because 7x7=49, and 5x5=25

Test your function with some dummy inputs. Does it work for all possible inputs?

In [34]:
def square_digits(input_number):
  # Convert the number to a string to extract individual digits
  N_str = str(N)

  # Square each digit and concatenate the results
  result = ''.join(str(int(digit)**2) for digit in N_str)

  return int(result)


N = 75
square_digits(N)

4925

# Part 2: Indexing

#### **Building a Vocabulary**

Lets start with 5 documents, where each document is just a simple sentence

In [35]:
# documents to be indexed
documents = ['Boats are great',
             'Sailing boats are enviromental',
             'canal boats are narrow',
             'wooden boats are more work than metal boats',
             'a wooden boat is always the prettiest']

# documents combined
document_terms = [doc.split(' ') for doc in documents]

For demonstration purposes, we'll now build the index step by step. Note that there is a much quicker method which we'll show later.

In [36]:
# First we need to build the "vocabulary" i.e all the words in the docs.

vocabulary = set()

for doc in documents:
  for word in doc.split():
    vocabulary.add(word)

vocabulary = list(vocabulary)

vocabulary

['metal',
 'wooden',
 'are',
 'narrow',
 'enviromental',
 'a',
 'Sailing',
 'is',
 'the',
 'prettiest',
 'than',
 'more',
 'canal',
 'always',
 'work',
 'boats',
 'great',
 'Boats',
 'boat']

In [37]:
# CODING TIP: You can also write this in a single line
vocabulary2 = list(set(word for doc in documents for word in doc.split()))

# Lets check that the two methods lead to the same result
vocabulary == vocabulary2

True

**Question**: Why do we build the vocabulary using a python set and not a list?

If you are struggling to understand why.. try to build the the vocabulary using a list instead of a set. What are the differences?

#### **Building a binary term-document matrix**

We can represent each document as a binary term-document matrix to show if a term features in that document or not

In [38]:
# binary term-document matrix representation of all docs
binary_term_doc = [[ 1 if term in doc else 0 for term in vocabulary] for doc in document_terms]

binary_term_doc

[[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
 [0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
 [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0],
 [0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1]]

In [39]:
# CODING TIP: Alternatively you can also cast the boolean result of evaluating term in doc to an int
binary_term_doc2 = [[int(term in doc) for term in vocabulary] for doc in document_terms]

# Sanity check: Lets check that the two methods lead to the same result
binary_term_doc2 == binary_term_doc

True

In [40]:
# Show in pandas for good visualisation
binary_term_doc_df = pd.DataFrame(binary_term_doc2, columns = vocabulary)
binary_term_doc_df

,metal,wooden,are,narrow,enviromental,a,Sailing,is,the,prettiest,than,more,canal,always,work,boats,great,Boats,boat
0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0
1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0
2,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0
3,1,1,1,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,0
4,0,1,0,0,0,1,0,1,1,1,0,0,0,1,0,0,0,0,1

#### **Term Occurence and Document Frequency**

In [41]:
# An important part of the index is a dictionary that tells us which documents contain which words, otherwise known as the term occurence dictionary. So let's create one
term_occurence = {term:[] for term in vocabulary}

for doc_id, doc in enumerate(document_terms):
  for term in doc:
    term_occurence[term].append(doc_id)

In [42]:
term_occurence

{'metal': [3],
 'wooden': [3, 4],
 'are': [0, 1, 2, 3],
 'narrow': [2],
 'enviromental': [1],
 'a': [4],
 'Sailing': [1],
 'is': [4],
 'the': [4],
 'prettiest': [4],
 'than': [3],
 'more': [3],
 'canal': [2],
 'always': [4],
 'work': [3],
 'boats': [1, 2, 3, 3],
 'great': [0],
 'Boats': [0],
 'boat': [4]}

In [43]:
# CODING TIP: We can also use the defaultdict module from the collections package
# This dictionary implementation has a little more functionality, that may come in useful later.
from collections import defaultdict

term_occurence = defaultdict(list)

for doc_id, doc in enumerate(document_terms):
  for term in doc:
    term_occurence[term].append(doc_id)

In [44]:
term_occurence

defaultdict(list,
            {'Boats': [0],
             'are': [0, 1, 2, 3],
             'great': [0],
             'Sailing': [1],
             'boats': [1, 2, 3, 3],
             'enviromental': [1],
             'canal': [2],
             'narrow': [2],
             'wooden': [3, 4],
             'more': [3],
             'work': [3],
             'than': [3],
             'metal': [3],
             'a': [4],
             'boat': [4],
             'is': [4],
             'always': [4],
             'the': [4],
             'prettiest': [4]})

The **term occurence dictionary** can be used to calculate the **document frequency** for each term. i.e how many documents does each term appear in. This is an important measure that we'll see again in later labs

In [45]:
doc_frequency = {keys: len(values) for (keys, values) in term_occurence.items()}
doc_frequency

{'Boats': 1,
 'are': 4,
 'great': 1,
 'Sailing': 1,
 'boats': 4,
 'enviromental': 1,
 'canal': 1,
 'narrow': 1,
 'wooden': 2,
 'more': 1,
 'work': 1,
 'than': 1,
 'metal': 1,
 'a': 1,
 'boat': 1,
 'is': 1,
 'always': 1,
 'the': 1,
 'prettiest': 1}

#### **Term-document count matrix**

We have just explored code that calculates the binary term-document matrix. This representation is simple to calculate but it has its limitations.

What if some documents contain many occurences of the same term? It could be important to give more weight to these term when trying to retrieve the correct document. The binary term-document matrix cannot represent this information..

Lets introduce the **term-document count matrix** where we count the number of occurences of each vocab term in each document.

What differences do you expect to see?

In [46]:
documents

['Boats are great',
 'Sailing boats are enviromental',
 'canal boats are narrow',
 'wooden boats are more work than metal boats',
 'a wooden boat is always the prettiest']

In [47]:
# binary term-document matrix we calculated early

binary_term_doc_df

,metal,wooden,are,narrow,enviromental,a,Sailing,is,the,prettiest,than,more,canal,always,work,boats,great,Boats,boat
0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0
1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0
2,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0
3,1,1,1,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,0
4,0,1,0,0,0,1,0,1,1,1,0,0,0,1,0,0,0,0,1

In [48]:
# term-document count matrix representation for all docs

# first create an matrix full of zeros
term_doc_count_matrix = np.zeros((len(document_terms), len(vocabulary)), dtype=int)

# iterate over the documents
for i, doc in enumerate(document_terms):
  # iterate over the terms in each document
  for term in doc:
    # find if a term is in our vocab
    if term in vocabulary:
      j = vocabulary.index(term) # find index of term in vocab
      term_doc_count_matrix[i, j] += 1

term_doc_count_df = pd.DataFrame(term_doc_count_matrix, columns = vocabulary)
term_doc_count_df

,metal,wooden,are,narrow,enviromental,a,Sailing,is,the,prettiest,than,more,canal,always,work,boats,great,Boats,boat
0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0
1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0
2,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0
3,1,1,1,0,0,0,0,0,0,0,1,1,0,0,1,2,0,0,0
4,0,1,0,0,0,1,0,1,1,1,0,0,0,1,0,0,0,0,1

Spot the difference?

We mentioned previously that there was a quicker method for computing our term-document indices. It uses sklearn's **CountVectorizer**

In [49]:
from sklearn.feature_extraction.text import CountVectorizer

In [50]:
# See https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
# binary = True returns the binary term-document matrix, while binary=False returns the term-document count matrix
vectorizer = CountVectorizer(binary=False)

In [51]:
binary_term_doc = vectorizer.fit_transform(documents)
# a sparse matrix representaion of the data (lower memory consumption, especially useful for large documents). this is easy to turn into a numpy array with .toarray()
# however, don't do it unless you have to as it is costly
binary_term_doc

<5x17 sparse matrix of type '<class 'numpy.int64'>'
	with 24 stored elements in Compressed Sparse Row format>

In [52]:
vocabulary = vectorizer.get_feature_names_out()
vocabulary

array(['always', 'are', 'boat', 'boats', 'canal', 'enviromental', 'great',
       'is', 'metal', 'more', 'narrow', 'prettiest', 'sailing', 'than',
       'the', 'wooden', 'work'], dtype=object)

In [53]:
# visualise using pandas
df = pd.DataFrame(binary_term_doc.toarray(), columns=vocabulary)
df

# CODING TIP: numpy and pandas functions are often faster than using python's inbuilt iterators (for, while) due to vectorizing.

,always,are,boat,boats,canal,enviromental,great,is,metal,more,narrow,prettiest,sailing,than,the,wooden,work
0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
1,0,1,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0
2,0,1,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0
3,0,1,0,2,0,0,0,0,1,1,0,0,0,1,0,1,1
4,1,0,1,0,0,0,0,1,0,0,0,1,0,0,1,1,0

### Question 1:
Do you notice anything different about the vocabulary when using Count Vectorizer compared to the vocabulary of our longer method?

Answer: there is some basic preprocessing to the input string such as: lower case for all terms, stop words removed.

### Question 2:

What other methods can be used to preprocess words (tokens) in a corpus of text documents? Describe two

Answer: stemming and lemmantization.

### Question 3:
Write code to calculate the term frequency of the word 'boats' in the 3rd document

In [55]:
# your code goes here
term_doc_count_df.loc[2, 'boats']

1

### Question 4:
Write code to calculate the document frequency of the word 'are'

In [ ]:
# your code goes here

In [56]:
doc_frequency['are']

4